- hosts: 127.0.0.1
  connection: local
  user: vagrant
  sudo: yes
  roles:
    - role: zzet.rbenv
      rbenv_users: vagrant
      rbenv:
        env: user
        version: v0.4.0
        ruby_version: 2.0.0-p645

    - role: djyugg.nodebrew
      nodebrew_nodejs_version: v0.10.25

    - role: geerlingguy.php

    - role: ansiblebit.oracle-java
      oracle_java_version: 8
      oracle_java_state: latest
